import React from 'react'
import Frame from 'src/component/frame/frame.jsx'

const About = () => (
    <Frame>
    <h1>Article title</h1>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mattis pellentesque id nibh tortor id aliquet lectus. Nullam non nisi est sit amet facilisis magna etiam. Tellus mauris a diam maecenas sed enim ut sem. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Id aliquet lectus proin nibh nisl condimentum id. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Nec sagittis aliquam malesuada bibendum arcu vitae. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Leo vel orci porta non pulvinar neque laoreet. Gravida dictum fusce ut placerat. Cursus turpis massa tincidunt dui ut. Ut sem nulla pharetra diam. Nibh cras pulvinar mattis nunc. Quisque egestas diam in arcu cursus. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Egestas quis ipsum suspendisse ultrices gravida. At tellus at urna condimentum mattis pellentesque id.

Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Ut venenatis tellus in metus vulputate. Tempus imperdiet nulla malesuada pellentesque elit eget. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Nam at lectus urna duis convallis convallis tellus. Viverra nibh cras pulvinar mattis nunc. Mattis aliquam faucibus purus in massa tempor. A diam maecenas sed enim ut sem viverra aliquet. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Consequat id porta nibh venenatis cras sed felis eget velit. Interdum varius sit amet mattis. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Dis parturient montes nascetur ridiculus mus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Consequat ac felis donec et odio pellentesque diam. Lectus proin nibh nisl condimentum id venenatis a condimentum vitae. Ut ornare lectus sit amet est placerat in egestas erat.

Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Egestas diam in arcu cursus. Ut tortor pretium viverra suspendisse potenti nullam ac. Morbi leo urna molestie at elementum. Ipsum dolor sit amet consectetur adipiscing elit. Vitae et leo duis ut diam. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. Sit amet consectetur adipiscing elit pellentesque habitant. Tellus id interdum velit laoreet id.

Duis at tellus at urna. Nulla aliquet porttitor lacus luctus accumsan. Nulla malesuada pellentesque elit eget gravida. Arcu odio ut sem nulla pharetra diam sit amet nisl. Nibh tellus molestie nunc non blandit. Ultrices gravida dictum fusce ut placerat orci. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Lobortis scelerisque fermentum dui faucibus in. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. In dictum non consectetur a erat nam at lectus. Sed odio morbi quis commodo odio aenean sed adipiscing. Morbi quis commodo odio aenean. Suspendisse sed nisi lacus sed viverra tellus in hac. In cursus turpis massa tincidunt. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet.

Sit amet porttitor eget dolor morbi non arcu. Laoreet non curabitur gravida arcu ac. Vitae auctor eu augue ut lectus arcu bibendum at varius. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. At ultrices mi tempus imperdiet nulla. Risus sed vulputate odio ut enim blandit. Maecenas ultricies mi eget mauris pharetra et. Porttitor eget dolor morbi non arcu risus quis. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Vestibulum rhoncus est pellentesque elit ullamcorper. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Curabitur vitae nunc sed velit. Amet venenatis urna cursus eget nunc. Non nisi est sit amet facilisis magna etiam tempor orci. Aliquet sagittis id consectetur purus ut faucibus pulvinar.
    </Frame>
);

export default About;
