import React from 'react'
import Frame from 'src/component/frame/frame.jsx'

const About = () => (
    <Frame>
    <h1>Article title</h1>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus at ultrices mi tempus imperdiet. Justo laoreet sit amet cursus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Nibh cras pulvinar mattis nunc. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ut sem nulla pharetra diam. Sit amet dictum sit amet justo. Eros in cursus turpis massa tincidunt. Hendrerit dolor magna eget est lorem ipsum. Duis at tellus at urna condimentum mattis. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. A erat nam at lectus urna.
    Nec dui nunc mattis enim ut tellus elementum sagittis. Odio morbi quis commodo odio aenean sed adipiscing diam. Turpis in eu mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula. Convallis posuere morbi leo urna molestie at. Tellus pellentesque eu tincidunt tortor. Est ullamcorper eget nulla facilisi etiam dignissim. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lacus laoreet non curabitur gravida arcu ac tortor. In ante metus dictum at tempor commodo ullamcorper a. Amet facilisis magna etiam tempor. Eget est lorem ipsum dolor sit amet consectetur. Ornare arcu odio ut sem nulla pharetra diam sit amet. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Duis tristique sollicitudin nibh sit amet. Quis eleifend quam adipiscing vitae proin sagittis nisl. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor.
    Ultrices tincidunt arcu non sodales. Viverra adipiscing at in tellus integer feugiat scelerisque. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Vitae turpis massa sed elementum tempus. Arcu dictum varius duis at consectetur lorem donec massa. Nunc sed blandit libero volutpat sed. Odio tempor orci dapibus ultrices in iaculis nunc. Massa eget egestas purus viverra. Turpis egestas maecenas pharetra convallis posuere morbi. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Vitae purus faucibus ornare suspendisse sed nisi.
    Integer vitae justo eget magna fermentum iaculis eu non. Mauris vitae ultricies leo integer malesuada. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ut eu sem integer vitae justo eget magna fermentum. Augue mauris augue neque gravida. Mauris in aliquam sem fringilla. Enim sed faucibus turpis in eu. Cursus eget nunc scelerisque viverra mauris in aliquam. Enim eu turpis egestas pretium aenean pharetra magna. Pellentesque habitant morbi tristique senectus et. Neque vitae tempus quam pellentesque. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Vestibulum rhoncus est pellentesque elit ullamcorper. Gravida neque convallis a cras. Odio ut sem nulla pharetra diam sit. Pellentesque adipiscing commodo elit at imperdiet. Velit dignissim sodales ut eu sem. Cras ornare arcu dui vivamus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.
    Quis vel eros donec ac. Phasellus vestibulum lorem sed risus ultricies tristique. Montes nascetur ridiculus mus mauris vitae. Tristique nulla aliquet enim tortor at auctor. Elementum nibh tellus molestie nunc non. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Quis viverra nibh cras pulvinar mattis nunc sed. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Mattis rhoncus urna neque viverra justo nec ultrices dui. Duis convallis convallis tellus id interdum velit laoreet id. Enim nunc faucibus a pellentesque sit. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Amet aliquam id diam maecenas ultricies. Quis hendrerit dolor magna eget est lorem ipsum. Sed nisi lacus sed viverra tellus in hac.
    Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Tempus egestas sed sed risus pretium quam vulputate. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Ultrices dui sapien eget mi proin sed libero. Nibh tellus molestie nunc non. Massa tincidunt dui ut ornare lectus sit amet est. Eget nullam non nisi est sit amet facilisis magna etiam. Diam sit amet nisl suscipit adipiscing. Pulvinar sapien et ligula ullamcorper malesuada. Varius sit amet mattis vulputate enim nulla.
    Congue nisi vitae suscipit tellus mauris a. Quisque id diam vel quam elementum pulvinar etiam non quam. Turpis egestas maecenas pharetra convallis posuere morbi leo. Etiam sit amet nisl purus in mollis. Ultricies mi quis hendrerit dolor magna. Augue lacus viverra vitae congue eu consequat ac. Non consectetur a erat nam at lectus. Et netus et malesuada fames ac. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Justo donec enim diam vulputate ut pharetra sit. Et malesuada fames ac turpis egestas maecenas pharetra convallis. In cursus turpis massa tincidunt dui.
    Sed elementum tempus egestas sed sed risus pretium quam vulputate. Neque sodales ut etiam sit amet nisl purus in. A lacus vestibulum sed arcu non odio euismod lacinia. Gravida neque convallis a cras semper auctor neque vitae. Senectus et netus et malesuada fames ac turpis egestas sed. Purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Sit amet justo donec enim diam vulputate. Tristique sollicitudin nibh sit amet. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Ac turpis egestas sed tempus urna. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Risus ultricies tristique nulla aliquet enim. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Facilisis sed odio morbi quis commodo odio aenean sed. Faucibus interdum posuere lorem ipsum dolor sit. Neque sodales ut etiam sit. Consectetur lorem donec massa sapien faucibus et molestie ac.
    <h2>Heading Two</h2>
    Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Aliquam malesuada bibendum arcu vitae. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Mi proin sed libero enim sed faucibus turpis in eu. Tortor condimentum lacinia quis vel. Ornare arcu odio ut sem nulla. Aenean euismod elementum nisi quis. Neque vitae tempus quam pellentesque nec nam. Augue interdum velit euismod in. Facilisis sed odio morbi quis commodo. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Diam sollicitudin tempor id eu nisl nunc. In mollis nunc sed id semper risus in. Nulla pharetra diam sit amet nisl. Sed faucibus turpis in eu mi bibendum. Diam donec adipiscing tristique risus nec feugiat in. Et odio pellentesque diam volutpat. Sit amet justo donec enim diam vulputate ut pharetra.
    Tellus in hac habitasse platea. Viverra aliquet eget sit amet tellus cras adipiscing. Placerat duis ultricies lacus sed. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Senectus et netus et malesuada fames ac. Auctor urna nunc id cursus metus. Commodo odio aenean sed adipiscing diam. Morbi leo urna molestie at. Varius morbi enim nunc faucibus a. Suscipit adipiscing bibendum est ultricies integer quis. Auctor elit sed vulputate mi sit. Id leo in vitae turpis massa.
    Gravida arcu ac tortor dignissim convallis aenean. Dolor sit amet consectetur adipiscing elit. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Tristique et egestas quis ipsum suspendisse. At lectus urna duis convallis convallis. Turpis massa sed elementum tempus egestas sed sed risus pretium. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Lobortis mattis aliquam faucibus purus. Nibh nisl condimentum id venenatis a. Massa sapien faucibus et molestie. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus.
    <h3>Heading Three</h3>
    Tristique senectus et netus et malesuada. Facilisi etiam dignissim diam quis enim. Commodo odio aenean sed adipiscing diam. Elementum sagittis vitae et leo duis ut diam quam nulla. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Sed elementum tempus egestas sed. Magna ac placerat vestibulum lectus. Arcu dui vivamus arcu felis bibendum ut tristique et. Diam maecenas ultricies mi eget mauris. Consectetur libero id faucibus nisl tincidunt. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Tellus rutrum tellus pellentesque eu tincidunt. Risus pretium quam vulputate dignissim suspendisse in est ante.
    Vulputate dignissim suspendisse in est ante. Nunc sed velit dignissim sodales ut eu. Auctor eu augue ut lectus arcu bibendum at. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Mollis aliquam ut porttitor leo. Mi eget mauris pharetra et ultrices neque ornare. Faucibus interdum posuere lorem ipsum dolor sit amet. In nisl nisi scelerisque eu. Dictum sit amet justo donec. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Ultrices dui sapien eget mi proin sed libero enim sed.
    Arcu cursus euismod quis viverra nibh cras. Mauris in aliquam sem fringilla. Rutrum quisque non tellus orci ac auctor augue. Massa tempor nec feugiat nisl pretium fusce id velit. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Eu sem integer vitae justo. Nisi porta lorem mollis aliquam ut porttitor. Dignissim convallis aenean et tortor at. Purus sit amet volutpat consequat mauris nunc congue nisi. Vel quam elementum pulvinar etiam non. Nisi porta lorem mollis aliquam. Euismod quis viverra nibh cras. Nibh tellus molestie nunc non blandit. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Mattis pellentesque id nibh tortor id aliquet lectus. Netus et malesuada fames ac turpis egestas. Magna ac placerat vestibulum lectus. Elementum facilisis leo vel fringilla est ullamcorper eget. Fusce ut placerat orci nulla pellentesque dignissim enim sit.
    Massa enim nec dui nunc mattis. Et netus et malesuada fames ac. Montes nascetur ridiculus mus mauris vitae ultricies. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Quam viverra orci sagittis eu volutpat odio facilisis. Amet justo donec enim diam. Mi sit amet mauris commodo. Mattis molestie a iaculis at erat pellentesque. Magna eget est lorem ipsum dolor sit amet consectetur. Vitae auctor eu augue ut lectus arcu bibendum at varius. Tortor at auctor urna nunc id cursus. Aliquet bibendum enim facilisis gravida neque. Orci porta non pulvinar neque laoreet suspendisse. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Ut consequat semper viverra nam libero. A erat nam at lectus urna duis convallis convallis tellus.
    </Frame>
);

export default About;
